Add pyunit tests case
arctouch/web-tests-factory pull request #5
Opened 2021-09-21 23:11 UTC by joaomarcuslf

I've fixed the error when trying to use number 2 for pyunit and added the first cases for pyunit.

## Generated files:
![Screen Shot 2021-09-21 at 20 06 51](https://user-images.githubusercontent.com/53450523/134259395-095310dd-278e-421e-808f-fc04e9c8695a.png)

## Running the tests:
![Screen Shot 2021-09-21 at 20 07 01](https://user-images.githubusercontent.com/53450523/134259403-eb52d537-2aa7-4687-819b-97b7ded20a75.png)

2021-09-23 00:18 UTC, arctouch-leticiacoelho requested changes
Your contribution is soo amazing! 
THANK YOU A LOT! 🧡
 To finish this PR, please, just follow the instruction 3 on the [contribute file.](https://github.com/arctouch/web-tests-factory/blob/main/contribute.md)

**_3. On this project, insert your new test inside the folder: defaultTests/yourFrameworkName. It won't do anything, it is just an example in order to see all the tests available in the script._**

Thank you! You are awesome!

2021-09-23 13:07 UTC, joaomarcuslf commented
> Your contribution is soo amazing!
> THANK YOU A LOT! 🧡
> To finish this PR, please, just follow the instruction 3 on the [contribute file.](https://github.com/arctouch/web-tests-factory/blob/main/contribute.md)
> 
> **_3. On this project, insert your new test inside the folder: defaultTests/yourFrameworkName. It won't do anything, it is just an example in order to see all the tests available in the script._**
> 
> Thank you! You are awesome!

I've added to this and the Rspec PR

2021-09-24 12:35 UTC, arctouch-leticiacoelho submitted a review, later dismissed
Thanks a lot for your contribution! 
You are the best 🧡

2021-09-24 17:21 UTC, arctouch-leticiacoelho approved these changes

2021-09-24 17:22 UTC, merged